# Generated by Django 5.2.8 on 2025-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.IntegerField()),
                ("cname", models.CharField(max_length=30)),
                ("unm", models.CharField(max_length=30)),
                ("pw", models.CharField(max_length=30)),
            ],
        ),
    ]
