# Generated by Django 5.2.8 on 2025-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayShopApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="cid",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="customer",
            name="cadd",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
