# Generated by Django 5.2.8 on 2025-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayShopApp", "0002_rename_cid_customer_phone_customer_cadd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
