# Generated by Django 5.2.8 on 2025-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayShopApp", "0004_imageuploader"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageuploader",
            name="name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="imageuploader",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="imageuploader",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
