# Generated by Django 5.2.8 on 2025-11-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zayShopApp", "0006_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="", max_length=30),
        ),
    ]
